import type { CollectionConfig } from 'payload'

export const Variants: CollectionConfig = {
  slug: 'variants',
  admin: {
    useAsTitle: 'id',
    group: 'Products',
  },
  access: {
    read: () => true,
    create: ({ req: { user } }) => Boolean(user),
    update: ({ req: { user } }) => Boolean(user),
    delete: ({ req: { user } }) => Boolean(user),
  },
  fields: [
    {
      name: 'product',
      type: 'relationship',
      relationTo: 'products',
      required: true,
      hasMany: false,
    },
    {
      name: 'size',
      type: 'select',
      required: true,
      options: [
        { label: 'XS', value: 'XS' },
        { label: 'S', value: 'S' },
        { label: 'M', value: 'M' },
        { label: 'L', value: 'L' },
        { label: 'XL', value: 'XL' },
        { label: '2XL', value: '2XL' },
        { label: '3XL', value: '3XL' },
        { label: '4XL', value: '4XL' },
        { label: '5XL', value: '5XL' },
        { label: '6XL', value: '6XL' },
        { label: 'Free', value: 'Free' },
      ],
    },
    {
      name: 'color',
      type: 'select',
      required: true,
      options: [
        { label: 'White', value: 'white' },
        { label: 'Off White', value: 'off-white' },
        { label: 'Cream', value: 'cream' },
        { label: 'Ivory', value: 'ivory' },
        { label: 'Beige', value: 'beige' },
        { label: 'Nude', value: 'nude' },
        { label: 'Black', value: 'black' },
        { label: 'Charcoal', value: 'charcoal' },
        { label: 'Grey', value: 'grey' },
        { label: 'Silver', value: 'silver' },
        { label: 'Taupe', value: 'taupe' },
        { label: 'Red', value: 'red' },
        { label: 'Maroon', value: 'maroon' },
        { label: 'Burgundy', value: 'burgundy' },
        { label: 'Wine', value: 'wine' },
        { label: 'Crimson', value: 'crimson' },
        { label: 'Ruby', value: 'ruby' },
        { label: 'Cherry', value: 'cherry' },
        { label: 'Rose', value: 'rose' },
        { label: 'Pink', value: 'pink' },
        { label: 'Hot Pink', value: 'hot-pink' },
        { label: 'Fuchsia', value: 'fuchsia' },
        { label: 'Magenta', value: 'magenta' },
        { label: 'Blush', value: 'blush' },
        { label: 'Peach', value: 'peach' },
        { label: 'Coral', value: 'coral' },
        { label: 'Salmon', value: 'salmon' },
        { label: 'Orange', value: 'orange' },
        { label: 'Tangerine', value: 'tangerine' },
        { label: 'Rust', value: 'rust' },
        { label: 'Mustard', value: 'mustard' },
        { label: 'Yellow', value: 'yellow' },
        { label: 'Gold', value: 'gold' },
        { label: 'Saffron', value: 'saffron' },
        { label: 'Amber', value: 'amber' },
        { label: 'Green', value: 'green' },
        { label: 'Olive', value: 'olive' },
        { label: 'Emerald', value: 'emerald' },
        { label: 'Mint', value: 'mint' },
        { label: 'Teal', value: 'teal' },
        { label: 'Sage', value: 'sage' },
        { label: 'Mehendi', value: 'mehendi' },
        { label: 'Pista', value: 'pista' },
        { label: 'Blue', value: 'blue' },
        { label: 'Navy Blue', value: 'navy-blue' },
        { label: 'Royal Blue', value: 'royal-blue' },
        { label: 'Sky Blue', value: 'sky-blue' },
        { label: 'Turquoise', value: 'turquoise' },
        { label: 'Indigo', value: 'indigo' },
        { label: 'Cobalt', value: 'cobalt' },
        { label: 'Purple', value: 'purple' },
        { label: 'Lavender', value: 'lavender' },
        { label: 'Lilac', value: 'lilac' },
        { label: 'Violet', value: 'violet' },
        { label: 'Plum', value: 'plum' },
        { label: 'Mauve', value: 'mauve' },
        { label: 'Brown', value: 'brown' },
        { label: 'Tan', value: 'tan' },
        { label: 'Coffee', value: 'coffee' },
        { label: 'Khaki', value: 'khaki' },
      ],
    },
    {
      name: 'blouseSize',
      type: 'text',
    },
    {
      name: 'sku',
      type: 'text',
      unique: true,
    },
    {
      name: 'stock',
      type: 'number',
      min: 0,
      defaultValue: 0,
    },
    {
      name: 'priceOverride',
      type: 'number',
      min: 0,
    },
  ],
  timestamps: true,
}
